/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class jni_test_Method */

#ifndef _Included_jni_test_Method
#define _Included_jni_test_Method
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_test_Method
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jni_test_Method_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jni_test_Method
 * Method:    minus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jni_test_Method_minus
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jni_test_Method
 * Method:    otherMethod
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jni_test_Method_otherMethod
  (JNIEnv *, jobject, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
